apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: builder
rules:
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["projectriff.io"]
    resources: ["functions", "topics"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: builder
roleRef:
  kind: Role
  name: builder
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: builder